"""
Dynamic, column-aware feature engineering for loan risk.

THE ONE RULE THAT MATTERS
-------------------------
This is a panel. Every history feature is computed with an expanding
window over rows 1..t for the row at t -- never t+1 onward. At scoring
time for row t we know everything up to and including t, and the targets
describe t+1..t+12, so including row t itself is correct and NOT leakage.
Using `.rolling()` without grouping, or any centred window, would be.
`tests/test_features.py` pins this with a fixture whose future is
deliberately explosive.

WHAT THIS ADDS OVER THE RAW COLUMNS
-----------------------------------
Three families, each earning its place:

  AMORTISATION   Where is this loan against its own schedule? A loan
                 paying ahead of schedule behaves differently from one
                 that has been capitalised. `amortisation_gap` is the
                 signed difference between actual and scheduled balance
                 ratio, reusing the same closed-form projection the
                 transition engine uses for forward simulation.

  RATE INCENTIVE The phase-1 transition model scored ROC-AUC ~0.50 on
                 prepayment -- no signal whatsoever. That is expected:
                 prepayment is driven by the gap between the borrower's
                 rate and what they could refinance into, and no column
                 in the pack carries a market rate. We reconstruct one
                 from the pack itself: the mean origination rate of loans
                 originated in each calendar month. `rate_incentive` is
                 the borrower's rate minus that. Positive means paying
                 above market, which is the refinance motive.

  DELINQUENCY    Current status is one frame of a film. A loan that has
  HISTORY        never missed a payment and one that has cured twice look
                 identical in `current_status` and completely different
                 in risk.

Features are created only if their source columns exist, so the pipeline
survives the organizer's real pack having a different schema. Every
feature is recorded in a manifest (name, formula, sources, rationale)
that feeds the model card.

PHASE: 3
STATUS: implemented.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import pandas as pd

from src.config import LOAN_ID_COLUMN, TIME_COLUMN

logger = logging.getLogger(__name__)

DPD_STATES = ("30DPD", "60DPD", "90DPD")
TERMINAL_STATES = ("Default", "Prepaid")

# Ordinal midpoints for the banded credit attributes. Banded strings are
# one-hot encoded by default, which throws away their ordering; a model
# should know that 620-659 sits below 660-699.
BAND_MIDPOINTS = {
    "credit_score_band": {
        "<620": 600, "620-659": 640, "660-699": 680, "700-739": 720,
        "740-779": 760, "780+": 800,
    },
    "ltv_band": {
        "<=60": 55, "61-70": 65, "71-80": 75, "81-90": 85, "91-95": 93,
        ">95": 98,
    },
    "dti_band": {
        "<=30": 25, "31-36": 33, "37-43": 40, "44-50": 47, ">50": 55,
    },
}


@dataclass
class FeatureManifest:
    """Every engineered feature, why it exists, and what it came from."""

    entries: list = field(default_factory=list)
    skipped: list = field(default_factory=list)

    def add(self, name, sources, formula, rationale, family):
        self.entries.append(
            {
                "feature": name,
                "family": family,
                "sources": ", ".join(sources),
                "formula": formula,
                "rationale": rationale,
            }
        )

    def skip(self, name, missing):
        self.skipped.append({"feature": name, "missing_columns": ", ".join(missing)})

    def to_frame(self) -> pd.DataFrame:
        return pd.DataFrame(self.entries)

    def feature_names(self) -> list:
        return [e["feature"] for e in self.entries]

    def to_markdown(self) -> str:
        lines = [
            "# Feature Manifest",
            "",
            "Generated by `src/features/engineering.py`. Every feature below "
            "is computed with an expanding window over a loan's own history "
            "up to and including the row being scored -- never beyond it.",
            "",
        ]
        for family in dict.fromkeys(e["family"] for e in self.entries):
            lines.append("## " + family)
            lines.append("")
            for e in self.entries:
                if e["family"] != family:
                    continue
                lines.append("**`{}`** — {}".format(e["feature"], e["rationale"]))
                lines.append("")
                lines.append("    {}".format(e["formula"]))
                lines.append("")
        if self.skipped:
            lines.append("## Not created (source columns absent)")
            lines.append("")
            for s in self.skipped:
                lines.append("- `{}` — needs {}".format(s["feature"], s["missing_columns"]))
        return "\n".join(lines)


def _has(df: pd.DataFrame, *cols) -> bool:
    return all(c in df.columns for c in cols)


def _missing(df: pd.DataFrame, cols) -> list:
    return [c for c in cols if c not in df.columns]


# ---------------------------------------------------------------------------
# Canonicalisation
# ---------------------------------------------------------------------------


def canonicalise_categories(df: pd.DataFrame, alias_map: dict = None) -> pd.DataFrame:
    """Fold the case-and-alias variants found by the profiler.

    `CA`, `ca` and `California` are one value. Left alone, a one-hot
    encoder learns three weak features instead of one strong one, and
    every segment-level scenario report splits California across three
    rows. Uses the profiler's explicit alias table, not fuzzy matching.
    """
    from src.data.profiler import KNOWN_ALIASES

    alias_map = alias_map or KNOWN_ALIASES
    out = df.copy()
    for col in ("state",):
        if col not in out.columns:
            continue
        folded = out[col].astype(str).str.strip().str.casefold()
        out[col] = folded.map(lambda v: alias_map.get(v, v)).str.upper()
        out.loc[df[col].isna(), col] = np.nan
    return out


# ---------------------------------------------------------------------------
# Feature families
# ---------------------------------------------------------------------------


def _scheduled_balance_ratio(age, term_total, monthly_rate):
    """Closed-form level-payment amortisation: fraction of principal left
    after `age` payments of a `term_total`-month loan."""
    with np.errstate(over="ignore", invalid="ignore", divide="ignore"):
        base = 1.0 + monthly_rate
        fN = np.power(base, term_total)
        ratio = (fN - np.power(base, age)) / (fN - 1.0)
    return np.where(np.isfinite(ratio), np.clip(ratio, 0.0, 1.0), np.nan)


def add_amortisation_features(df, m: FeatureManifest) -> pd.DataFrame:
    out = df.copy()
    fam = "Amortisation"

    if _has(out, "current_balance", "original_balance"):
        out["balance_ratio"] = (
            out["current_balance"] / out["original_balance"].replace(0, np.nan)
        ).clip(0, 2)
        m.add("balance_ratio", ["current_balance", "original_balance"],
              "current_balance / original_balance",
              "Scale-free paydown progress, so a $90k and a $900k loan at "
              "the same point in their life look alike to the model.", fam)
    else:
        m.skip("balance_ratio", _missing(out, ["current_balance", "original_balance"]))

    if _has(out, "loan_age_months", "remaining_term_months"):
        total = out["loan_age_months"] + out["remaining_term_months"]
        out["term_progress"] = (out["loan_age_months"] / total.replace(0, np.nan)).clip(0, 1)
        m.add("term_progress", ["loan_age_months", "remaining_term_months"],
              "loan_age / (loan_age + remaining_term)",
              "Position in the loan's life on a 0-1 scale. Hazard is "
              "strongly age-dependent and this normalises across terms.", fam)

        if _has(out, "interest_rate", "balance_ratio"):
            sched = _scheduled_balance_ratio(
                out["loan_age_months"].astype(float),
                total.astype(float),
                out["interest_rate"].astype(float) / 1200.0,
            )
            out["scheduled_balance_ratio"] = sched
            out["amortisation_gap"] = out["balance_ratio"] - sched
            m.add("amortisation_gap", ["balance_ratio", "interest_rate",
                                       "loan_age_months", "remaining_term_months"],
                  "balance_ratio - scheduled_balance_ratio(age, term, rate)",
                  "Signed distance from the contractual schedule. Negative "
                  "means paying ahead (a prepayment precursor); positive "
                  "means behind or capitalised (a deterioration signal).", fam)
    else:
        m.skip("term_progress", _missing(out, ["loan_age_months", "remaining_term_months"]))

    return out


def add_rate_incentive_features(df, m: FeatureManifest) -> pd.DataFrame:
    """Reconstruct a market rate from the pack and measure the gap to it.

    The pack ships no market-rate series, which is why the phase-1
    transition model had zero prepayment signal. The mean origination rate
    of loans originated in month t is a defensible proxy for what a
    borrower could refinance into at t: it is observable at t (those loans
    exist by then), so it introduces no lookahead.
    """
    out = df.copy()
    fam = "Rate incentive"
    needed = ["origination_month", "interest_rate"]
    if not _has(out, *needed):
        m.skip("rate_incentive", _missing(out, needed))
        return out

    rate_col = "original_interest_rate" if "original_interest_rate" in out.columns else "interest_rate"
    origination_rates = (
        out.drop_duplicates(LOAN_ID_COLUMN)
        .groupby(out.drop_duplicates(LOAN_ID_COLUMN)["origination_month"].dt.to_period("M"))[rate_col]
        .mean()
    )
    # Smooth and forward-fill: thin origination months would otherwise
    # produce a jumpy "market" rate driven by two or three loans.
    market = origination_rates.sort_index().rolling(3, min_periods=1).mean()

    key = out[TIME_COLUMN].dt.to_period("M")
    out["market_rate"] = key.map(market).astype(float)
    out["market_rate"] = out["market_rate"].ffill().bfill()
    out["rate_incentive"] = out["interest_rate"] - out["market_rate"]

    m.add("market_rate", ["origination_month", rate_col],
          "3-month rolling mean origination rate by calendar month",
          "Proxy for the prevailing rate a borrower could refinance into. "
          "Built only from loans already originated by that month, so it "
          "carries no lookahead.", fam)
    m.add("rate_incentive", ["interest_rate", "market_rate"],
          "interest_rate - market_rate",
          "The refinance motive. Positive means the borrower pays above "
          "market and has a reason to prepay. This is the feature the "
          "phase-1 model was missing when prepayment AUC came out at 0.50.", fam)

    # Absolute incentive does not transfer across time. Measured on this
    # panel: the top incentive quintile prepays at 30.2% in the training
    # window but only 14.8% in the test window, because the whole rate
    # environment moved -- which phase 2's adversarial validation had
    # already flagged, with interest_rate as the single largest source of
    # train/test separation. The percentile rank WITHIN each reporting
    # month asks the drift-robust version of the question: how strong is
    # this borrower's refinance motive relative to everyone else being
    # observed at the same time?
    out["rate_incentive_pctile"] = (
        out.groupby(out[TIME_COLUMN].dt.to_period("M"))["rate_incentive"]
        .rank(pct=True)
    )
    m.add("rate_incentive_pctile", ["rate_incentive", TIME_COLUMN],
          "percentile rank of rate_incentive within its reporting month",
          "Period-relative refinance motive. Uses only rows observed in the "
          "same month, so it introduces no lookahead, and it survives a "
          "shift in the rate environment that breaks the absolute version.", fam)
    return out


def add_delinquency_history(df, m: FeatureManifest) -> pd.DataFrame:
    """Backward-looking history. Expanding windows only, grouped by loan."""
    out = df.copy()
    fam = "Delinquency history"
    if "current_status" not in out.columns:
        m.skip("delinquency history block", ["current_status"])
        return out

    out = out.sort_values([LOAN_ID_COLUMN, TIME_COLUMN])
    g = out.groupby(LOAN_ID_COLUMN, sort=False)
    is_dpd = out["current_status"].isin(DPD_STATES).astype(int)

    out["months_delinquent_to_date"] = is_dpd.groupby(out[LOAN_ID_COLUMN]).cumsum()
    m.add("months_delinquent_to_date", ["current_status"],
          "expanding sum of (status in 30/60/90DPD), per loan",
          "Total delinquency exposure so far. Two loans that are Current "
          "today are not equally safe if one has missed six payments.", fam)

    out["ever_delinquent"] = (out["months_delinquent_to_date"] > 0).astype(int)
    m.add("ever_delinquent", ["current_status"],
          "months_delinquent_to_date > 0",
          "A blunt but powerful split: has this loan ever slipped at all.", fam)

    if "days_past_due" in out.columns:
        out["max_dpd_to_date"] = g["days_past_due"].cummax()
        m.add("max_dpd_to_date", ["days_past_due"],
              "expanding max of days_past_due, per loan",
              "Worst point reached. A loan that touched 90DPD and cured "
              "carries different risk from one that never passed 30.", fam)

    # Consecutive months in the CURRENT delinquency episode. Cumsum of a
    # run-id trick: each return to non-DPD starts a new group.
    episode = (is_dpd == 0).groupby(out[LOAN_ID_COLUMN]).cumsum()
    out["delinquency_streak"] = (
        is_dpd.groupby([out[LOAN_ID_COLUMN], episode]).cumsum()
    )
    m.add("delinquency_streak", ["current_status"],
          "consecutive months in the current DPD episode",
          "Distinguishes a one-month slip from a deepening roll. Roll rates "
          "out of 60DPD are far worse than out of a first 30DPD month.", fam)

    # A loan's first observation is not a change. Comparing it against the
    # NaN from the grouped shift makes `x != NaN` true and adds a phantom
    # change to every loan.
    prev_status = g["current_status"].shift(1)
    status_changed = (
        (out["current_status"] != prev_status) & prev_status.notna()
    ).astype(int)
    out["n_status_changes_to_date"] = (
        status_changed.groupby(out[LOAN_ID_COLUMN]).cumsum()
    )
    m.add("n_status_changes_to_date", ["current_status"],
          "expanding count of month-over-month status changes, per loan",
          "Volatility of the servicing record. Loans that oscillate are "
          "both riskier and more likely to carry data defects.", fam)

    if "balance_ratio" in out.columns:
        out["balance_change_3m"] = out["balance_ratio"] - g["balance_ratio"].shift(3)
        m.add("balance_change_3m", ["balance_ratio"],
              "balance_ratio(t) - balance_ratio(t-3), per loan",
              "Short-run paydown velocity. A sudden flattening precedes "
              "delinquency; a sudden drop precedes prepayment.", fam)

    if "modification_flag" in out.columns:
        out["ever_modified"] = (
            g["modification_flag"].cummax().fillna(0).astype(int)
        )
        m.add("ever_modified", ["modification_flag"],
              "expanding max of modification_flag, per loan",
              "A modification is a permanent change in the loan's character, "
              "not a one-month event.", fam)

    return out.sort_index()


def add_band_ordinals(df, m: FeatureManifest) -> pd.DataFrame:
    out = df.copy()
    fam = "Band ordinals"
    for col, mapping in BAND_MIDPOINTS.items():
        if col not in out.columns:
            m.skip(col + "_ordinal", [col])
            continue
        name = col + "_ordinal"
        out[name] = out[col].map(mapping)
        coverage = out[name].notna().mean()
        if coverage < 0.5:
            logger.warning(
                "%s mapped only %.0f%% of values; band labels may differ "
                "from the expected vocabulary", name, 100 * coverage
            )
        m.add(name, [col], "midpoint lookup of the band label",
              "Restores the ordering that one-hot encoding discards -- the "
              "model should know 620-659 sits below 660-699.", fam)
    return out


def add_data_quality_features(
    df, rule_flags=None, reconciliation_flags=None, quality_scores=None,
    m: FeatureManifest = None
) -> pd.DataFrame:
    """Carry the phase-2 outputs into the feature matrix.

    Measured in phase 2: rows where the servicer feed disagrees with the
    panel carry a 1.5x exception rate. That is a feature, not a footnote.
    """
    out = df.copy()
    fam = "Data quality"

    if rule_flags is not None and len(rule_flags.columns):
        out["rule_violation_count"] = rule_flags.reindex(out.index).fillna(False).sum(axis=1)
        m.add("rule_violation_count", ["validation_rules.json"],
              "number of deterministic rules violated by this record",
              "A record that fails logical checks is both more likely to be "
              "an exception and less trustworthy as model input.", fam)

    if reconciliation_flags is not None:
        for col, rationale in (
            ("source_conflict",
             "Servicer feed disagrees with the panel. Measured 1.5x exception lift."),
            ("source_stale",
             "The describing source updated long after (or impossibly before) the month."),
        ):
            if col in reconciliation_flags.columns:
                out[col] = reconciliation_flags[col].reindex(out.index).fillna(False).astype(int)
                m.add(col, ["servicer_updates.csv"], col, rationale, fam)
        if "servicer_update_lag_days" in reconciliation_flags.columns:
            out["servicer_update_lag_days"] = (
                reconciliation_flags["servicer_update_lag_days"].reindex(out.index).fillna(0)
            )
            m.add("servicer_update_lag_days", ["servicer_updates.csv"],
                  "last_updated_at - reporting_month, in days",
                  "Continuous staleness, rather than only the thresholded flag.", fam)

    if quality_scores is not None:
        out["data_quality_score"] = quality_scores.reindex(out.index).fillna(100.0)
        m.add("data_quality_score", ["profiler"],
              "0-100 composite of completeness, outlyingness, rule and source penalties",
              "Lets the model discount records it should trust less, instead "
              "of treating a defective row as equally informative.", fam)

    return out


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def engineer_features(
    df: pd.DataFrame,
    rule_flags: pd.DataFrame = None,
    reconciliation_flags: pd.DataFrame = None,
    quality_scores: pd.Series = None,
    manifest_path: Path | str = None,
) -> tuple:
    """Build the full feature matrix. Returns (dataframe, manifest)."""
    m = FeatureManifest()

    out = canonicalise_categories(df)
    out = add_amortisation_features(out, m)
    out = add_rate_incentive_features(out, m)
    out = add_delinquency_history(out, m)
    out = add_band_ordinals(out, m)
    out = add_data_quality_features(
        out, rule_flags, reconciliation_flags, quality_scores, m
    )

    if manifest_path is not None:
        Path(manifest_path).write_text(m.to_markdown(), encoding="utf-8")
        logger.info("Wrote feature manifest to %s", manifest_path)

    logger.info("Engineered %d features (%d skipped)", len(m.entries), len(m.skipped))
    return out, m
