"""
Build and validate submission.csv.

    python -m scripts.build_submission

Produces:
    submission.csv                     the graded deliverable
    docs/submission_report.md          what was produced and how it validated

Trains every component on the labelled panel and scores the unlabelled
test panel. The submission is written ONLY if validation passes -- an
invalid file that exists is worse than no file, because it looks done.

PHASE: 12
"""
from __future__ import annotations

import logging
import sys
import warnings
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

warnings.filterwarnings("ignore", category=FutureWarning)

from src.anomaly.exception_model import (  # noqa: E402
    rule_assigned_type,
    rule_covered_mask,
    train_exception_models,
)
from src.config import (  # noqa: E402
    configure_console,
    DATA_DIR, DOCS_DIR, LOAN_ID_COLUMN, MODELS_DIR, PROJECT_ROOT,
    STATE_ORDER, TIME_COLUMN,
)
from src.data.loader import load_data_pack  # noqa: E402
from src.explainability.error_analysis import temporal_ensemble_uncertainty  # noqa: E402
from src.explainability.labels import describe_rule  # noqa: E402
from src.explainability.shap_explainer import explain_model, source_column_map  # noqa: E402
from src.models.predict import (  # noqa: E402
    build_scoring_frame, score_anomalies, score_binary_targets, score_next_state,
)
from src.models.survival import (  # noqa: E402
    DiscreteTimeTransitionModel, EmpiricalTransitionBaseline, build_transition_frame,
)
from src.models.train import (  # noqa: E402
    BINARY_TARGETS, feature_columns, train_binary_target,
)
from src.submission import (  # noqa: E402
    build_submission, load_template_columns, validate_submission,
)

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
log = logging.getLogger("submission")

SUBMISSION_PATH = PROJECT_ROOT / "submission.csv"
CONFIDENCE_TARGET = "next_3m_delinquency_flag"


def main() -> None:
    configure_console()
    report: list = []

    def emit(text: str = "") -> None:
        report.append(text)

    def block(title: str, body: str) -> None:
        print("\n" + "=" * 72)
        print(title)
        print("=" * 72)
        print(body)
        emit()
        emit("## " + title)
        emit()
        emit("```")
        emit(body)
        emit("```")

    template_columns = load_template_columns()
    emit("# Submission Report")
    emit()
    emit("Generated by `scripts/build_submission.py`.")
    emit()
    emit("The schema is read from `data/submission_template.csv` at run "
         "time, not hardcoded, so a revised template is picked up rather "
         "than silently violated.")

    # ------------------------------------------------------------- data
    pack = load_data_pack(DATA_DIR)
    frame = build_scoring_frame(
        pack.train, pack.test, pack.static, pack.servicer_updates
    )
    block("1. Scoring frame", frame.summary())
    for note in frame.notes:
        emit()
        emit("> {}".format(note))

    train_features = frame.train
    score_features = frame.score

    # ------------------------------------------------- binary targets
    models = {}
    rows = []
    for target in BINARY_TARGETS:
        if target not in train_features.columns:
            continue
        log.info("Training %s", target)
        result = train_binary_target(train_features, target)
        if result.metrics.empty or not result.models:
            rows.append({"target": target, "status": "SKIPPED",
                         "champion": "-", "pr_auc": None})
            continue
        model, cols = result.models[result.champion]
        models[target] = (model, cols, result.calibration)
        best = result.metrics.sort_values("pr_auc", ascending=False).iloc[0]
        rows.append({
            "target": target,
            "status": "ok",
            "champion": result.champion,
            "pr_auc": best["pr_auc"],
            "calibration": result.calibration.method if result.calibration else "none",
        })
    block("2. Binary targets", pd.DataFrame(rows).to_string(index=False))

    probabilities = score_binary_targets(frame, models)

    # ------------------------------------------------------ next_state
    log.info("Fitting transition model")
    tf = build_transition_frame(train_features)
    transition = DiscreteTimeTransitionModel().fit(tf.data)
    next_state = score_next_state(frame, transition, STATE_ORDER)
    dist = next_state["next_state_pred"].value_counts()
    block("3. next_state predictions", dist.to_string())

    # ------------------------------------------------------- anomalies
    log.info("Scoring anomalies")
    anomaly = score_anomalies(frame)
    block("4. Anomaly detection", anomaly.summary())

    # ------------------------------------------------------ exceptions
    score_rule_flags = frame.rule_flags.loc[frame.score_index]
    covered = rule_covered_mask(score_rule_flags)
    types = rule_assigned_type(score_rule_flags)

    exc_model = train_exception_models(
        train_features, frame.rule_flags.loc[frame.train_index],
        anomaly_scores=None,
    )
    exceptions = pd.DataFrame(index=frame.score_index)
    exceptions["exception_required_pred"] = covered.astype(int)
    exceptions["exception_type_pred"] = types
    # Confidence reflects which mechanism decided: a fired rule is a fact
    # about the record, so it carries near-certainty; an unflagged record
    # carries the complement of its anomaly score, not a bare zero.
    exceptions["exception_confidence"] = np.where(
        covered, 0.98, (anomaly.scores.reindex(frame.score_index) * 0.5).clip(0, 0.49)
    )
    mix = exceptions["exception_required_pred"].value_counts().rename("n").to_frame()
    block("5. Exceptions", mix.to_string()
          + "\n\nby type:\n"
          + exceptions["exception_type_pred"].value_counts().to_string())
    for note in exc_model.notes:
        emit()
        emit("> {}".format(note))

    # ----------------------------------------------------- top drivers
    log.info("Computing SHAP drivers")
    driver_source = None
    for candidate in ("next_3m_delinquency_flag", "next_12m_default_flag"):
        if candidate in models:
            driver_source = candidate
            break

    if driver_source is None:
        top_drivers = pd.Series("not available", index=frame.score_index)
        emit()
        emit("> No champion available for SHAP drivers; `top_drivers` "
             "reports unavailability rather than inventing content.")
    else:
        model, cols, _ = models[driver_source]
        shap_result = explain_model(model, score_features, cols,
                                    sample=len(score_features))
        values = shap_result.values
        sources = np.array(shap_result.source_of)
        unique_sources = list(dict.fromkeys(sources))
        agg = np.zeros((values.shape[0], len(unique_sources)))
        for j, src in enumerate(unique_sources):
            agg[:, j] = values[:, sources == src].sum(axis=1)

        from src.explainability.labels import label as human_label
        labels = np.array([human_label(s) for s in unique_sources])
        order = np.argsort(-np.abs(agg), axis=1)[:, :3]
        driver_text = [
            "; ".join(
                "{} ({})".format(labels[j], "+" if agg[i, j] > 0 else "-")
                for j in order[i]
            )
            for i in range(len(agg))
        ]
        top_drivers = pd.Series(driver_text, index=shap_result.sample_index)
        top_drivers = top_drivers.reindex(frame.score_index)

        # A record the rules flagged gets the rule citation instead: a
        # deterministic reason beats an attribution for the same row.
        rule_text = score_rule_flags.apply(
            lambda r: "; ".join(describe_rule(c) for c in r.index if r[c]), axis=1
        )
        top_drivers = top_drivers.where(~covered, rule_text)
        emit()
        emit("`top_drivers` uses SHAP attributions from the `{}` champion, "
             "except on records a validation rule flagged -- those carry the "
             "rule citation instead, because a deterministic reason is more "
             "use to a reviewer than an attribution.".format(driver_source))

    # ------------------------------------------------- model confidence
    log.info("Estimating model confidence")
    cols = feature_columns(train_features)
    unc = temporal_ensemble_uncertainty(
        train_features, CONFIDENCE_TARGET, cols, score_features,
        n_splits=4, purge_months=3,
    )
    if unc.per_row.empty:
        model_confidence = pd.Series(np.nan, index=frame.score_index)
        emit()
        emit("> Model confidence could not be estimated: {}".format(
            "; ".join(unc.notes)))
    else:
        relative = unc.per_row["relative_spread"]
        # Rank-based so the column is a usable spread over [0,1] rather
        # than a heavy-tailed ratio squashed against one end.
        model_confidence = (1.0 - relative.rank(pct=True)).clip(0.01, 0.99)
        model_confidence.index = frame.score_index
        block("6. Model confidence", unc.summary())
        emit()
        emit("`model_confidence` is the complement of the percentile rank of "
             "prediction spread across models trained on different time "
             "windows. It answers 'how much does this score depend on when "
             "the model was trained', which is the failure that actually "
             "materialised for prepayment in phase 3.")

    # ---------------------------------------------------------- assemble
    keys = score_features[[LOAN_ID_COLUMN, TIME_COLUMN]]
    submission = build_submission(
        keys=keys,
        probabilities=probabilities,
        next_state=next_state,
        exceptions=exceptions,
        anomaly_scores=anomaly.scores,
        top_drivers=top_drivers,
        model_confidence=model_confidence,
        template_columns=template_columns,
    )

    validation = validate_submission(submission, pack.test, template_columns)
    block("7. Validation", validation.describe())

    block("8. Recommended actions",
          submission["recommended_action"].value_counts().to_string())
    emit()
    emit("Every value of `recommended_action` is a review instruction, not "
         "a decision about the loan. The column is produced by a "
         "deterministic policy over model outputs with published "
         "thresholds, not by a model.")

    block("9. Sample rows", submission.head(5).to_string(index=False,
                                                          max_colwidth=28))

    if validation.ok:
        submission.to_csv(SUBMISSION_PATH, index=False)
        joblib.dump({"models": models, "transition": transition},
                    MODELS_DIR / "submission_models.joblib")
        print("\nWrote {} ({:,} rows x {} columns)".format(
            SUBMISSION_PATH.name, len(submission), submission.shape[1]))
        emit()
        emit("Validation passed; `submission.csv` written with {:,} rows.".format(
            len(submission)))
    else:
        print("\nVALIDATION FAILED - submission.csv NOT written")
        for e in validation.errors:
            print("  " + e)
        emit()
        emit("**Validation failed, so no file was written.** An invalid "
             "submission that exists is worse than none, because it looks "
             "finished.")

    (DOCS_DIR / "submission_report.md").write_text(
        "\n".join(report) + "\n", encoding="utf-8")
    print("Wrote docs/submission_report.md")
    sys.exit(0 if validation.ok else 1)


if __name__ == "__main__":
    main()
