"""
Generate the model card from the run artifacts.

    python -m scripts.build_model_card

Produces:
    docs/model_card.md

The card is GENERATED, not written by hand. A hand-written card starts
accurate and drifts: a threshold moves, a champion changes, and the
document keeps reporting last week's numbers with total confidence.
Every figure here is read from the JSON snapshots the pipelines write, so
the card is either current or it fails loudly because a snapshot is
missing.

The prose sections -- limitations, known failure modes, leakage controls
-- are authored, because judgement does not come out of a JSON file. Each
one cites a measured number so the claim can be checked against the
artifact it came from.

PHASE: 13
"""
from __future__ import annotations

import json
import logging
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.config import (  # noqa: E402
    configure_console,
    DATA_DIR, DOCS_DIR, MODELS_DIR, RANDOM_SEED, STATE_ORDER,
)
from src.models.validation import TARGET_HORIZON_MONTHS  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
log = logging.getLogger("model_card")

TARGET_LABELS = {
    "next_3m_delinquency_flag": "3-month delinquency",
    "next_6m_delinquency_flag": "6-month delinquency",
    "next_12m_default_flag": "12-month default",
    "next_12m_prepayment_flag": "12-month prepayment",
}


def _load(path: Path, what: str):
    if not path.exists():
        raise FileNotFoundError(
            "{} not found at {}. Run the pipeline that produces it before "
            "building the model card -- the card reports measured numbers "
            "and will not invent them.".format(what, path)
        )
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> None:
    configure_console()
    supervised = _load(MODELS_DIR / "supervised_metrics.json", "supervised metrics")
    transition = _load(MODELS_DIR / "transition_artifacts.json", "transition artifacts")

    lines = []
    w = lines.append

    w("# Model Card — Loan Performance Intelligence Engine")
    w("")
    w("Generated by `scripts/build_model_card.py` from the artifacts in "
      "`models/`. Every metric is read from a snapshot written by the "
      "pipeline that produced it; none is transcribed by hand.")
    w("")

    # ------------------------------------------------------------ 1
    w("## 1. Objective")
    w("")
    w("Predict loan performance on a monthly loan-level panel, and give a "
      "reviewer enough context to act: multi-horizon delinquency, default "
      "and prepayment probabilities, next-state prediction, a data-quality "
      "exception verdict, an anomaly score, and the drivers behind each.")
    w("")
    w("Outputs are **advisory**. Nothing in this system decides a lending "
      "outcome; `recommended_action` in the submission emits only "
      "`REVIEW`, `MONITOR` or `NO ACTION`, and that constraint is enforced "
      "by a test rather than by convention.")
    w("")

    # ------------------------------------------------------------ 2
    w("## 2. Data")
    w("")
    w("| Table | Rows | Loans | Period |")
    w("|---|---|---|---|")
    for name, filename in (
        ("Training panel", "loan_monthly_performance_train.csv"),
        ("Test panel (unlabelled)", "loan_monthly_performance_test.csv"),
    ):
        path = DATA_DIR / filename
        if not path.exists():
            continue
        df = pd.read_csv(path, usecols=["loan_id", "reporting_month"])
        months = pd.to_datetime(df.reporting_month)
        w("| {} | {:,} | {:,} | {} to {} |".format(
            name, len(df), df.loan_id.nunique(),
            months.min().date(), months.max().date()))
    w("")
    w("> **This is synthetic data.** The pack was generated by "
      "`generate_synthetic_data.py` to match the shape of the challenge "
      "specification. No figure in this card describes real borrowers or "
      "real portfolio behaviour, and nothing here should be read as a "
      "finding about mortgage performance in the world.")
    w("")

    frame = transition.get("transition_frame", {})
    if frame:
        w("Panel construction for the transition model, after censoring:")
        w("")
        w("| Stage | Rows |")
        w("|---|---|")
        w("| Input rows | {:,} |".format(frame.get("input_rows", 0)))
        w("| Dropped, no t+1 observation | {:,} |".format(
            frame.get("terminal_rows_dropped", 0)))
        w("| Dropped, gap in the panel | {:,} |".format(
            frame.get("gap_rows_dropped", 0)))
        w("| Usable transitions | {:,} |".format(frame.get("usable", 0)))
        w("")

    # ------------------------------------------------------------ 3
    w("## 3. Features")
    w("")
    manifest = DOCS_DIR / "feature_manifest.md"
    w("Raw panel columns plus three engineered families — amortisation, "
      "rate incentive, and delinquency history — and the data-quality "
      "signals produced by the rule engine and source reconciliation. The "
      "full list with formulas and rationale is in "
      "[`feature_manifest.md`]({}).".format(manifest.name))
    w("")
    importance = DATA_DIR / "derived" / "global_importance.csv"
    if importance.exists():
        imp = pd.read_csv(importance)
        top = (imp[imp.target == "next_3m_delinquency_flag"]
               .nlargest(6, "mean_abs_shap"))
        if len(top):
            w("Most influential features for 3-month delinquency, by mean "
              "absolute SHAP (one-hot columns aggregated back to their "
              "source column):")
            w("")
            w("| Feature | Share of total attribution |")
            w("|---|---|")
            for r in top.itertuples():
                w("| {} | {:.1f}% |".format(r.label, r.share_pct))
            w("")

    # ------------------------------------------------------------ 4
    w("## 4. Models")
    w("")
    w("| Target | Type | Champion | Calibration |")
    w("|---|---|---|---|")
    for target, label in TARGET_LABELS.items():
        entry = supervised.get(target)
        if not entry:
            continue
        cal = (entry.get("calibration") or {}).get("method", "none")
        w("| {} | binary | {} | {} |".format(label, entry["champion"], cal))
    if "next_state" in supervised:
        w("| Next state | multiclass ({} states) | {} | n/a |".format(
            len(STATE_ORDER), supervised["next_state"]["champion"]))
    w("| Time-to-event | discrete-time multi-state hazard | "
      "per-origin multinomial, credibility-blended | held-out blend weight |")
    w("| Anomaly | unsupervised | Isolation Forest, target-blind | n/a |")
    w("| Exception | deterministic | rule engine over `validation_rules.json` | n/a |")
    w("")

    # ------------------------------------------------------------ 5
    w("## 5. Validation method")
    w("")
    w("Every split is chronological. This is a panel where the same loan "
      "appears in many rows, so a random row split puts one loan's March "
      "and April rows on opposite sides and the model memorises rather "
      "than generalises — a condition the challenge rules list as "
      "disqualifying.")
    w("")
    w("Splits additionally carry a **purge gap sized to each target's "
      "forward horizon**, because the labels look forward: without it, "
      "training rows carry labels determined by data inside the test "
      "period.")
    w("")
    w("| Target | Horizon | Purge gap |")
    w("|---|---|---|")
    for target, label in TARGET_LABELS.items():
        h = TARGET_HORIZON_MONTHS.get(target, 0)
        w("| {} | {} months | {} months |".format(label, h, h))
    w("")
    w("Rows whose forward window extends past the end of the panel are "
      "dropped from both training and evaluation, since their labels "
      "could not have been observed.")
    w("")

    # ------------------------------------------------------------ 6
    w("## 6. Metrics")
    w("")
    w("Held out, purged, and label-mature. PR-AUC is the headline rather "
      "than ROC-AUC: at prevalences between 0.9% and 9%, ROC-AUC is "
      "dominated by the majority class and flatters everything.")
    w("")
    w("| Target | Prevalence | Baseline PR-AUC | Final PR-AUC | Lift vs base rate | "
      "ROC-AUC | Recall @ 50% precision | Brier | ECE |")
    w("|---|---|---|---|---|---|---|---|---|")
    for target, label in TARGET_LABELS.items():
        entry = supervised.get(target)
        if not entry:
            continue
        metrics = pd.DataFrame(entry["metrics"])
        base = metrics[metrics.model.str.startswith("baseline")]
        final = metrics[metrics.calibrated] if metrics.calibrated.any() else metrics
        final = final.sort_values("pr_auc", ascending=False).iloc[0]
        w("| {} | {:.2%} | {} | {} | {}x | {} | {} | {} | {} |".format(
            label, final["prevalence"],
            base.iloc[0]["pr_auc"] if len(base) else "-",
            final["pr_auc"], final.get("pr_auc_lift", "-"),
            final["roc_auc"], final.get("recall_at_p50", "-"),
            final["brier"], final["ece"]))
    w("")

    ns = supervised.get("next_state")
    if ns:
        w("Next-state prediction, against two baselines:")
        w("")
        w("| Model | Accuracy | Macro-F1 | Log-loss |")
        w("|---|---|---|---|")
        for row in ns["metrics"]:
            w("| {} | {} | {} | {} |".format(
                row["model"], row["accuracy"], row["macro_f1"], row["log_loss"]))
        w("")
        w("The persistence baseline wins macro-F1 by refusing to predict "
          "change at all, and is 3.8x worse as a probability. It emits hard "
          "0/1 labels, cannot rank, and cannot fill "
          "`next_state_confidence`, so it is reported and excluded from "
          "champion selection.")
        w("")

    comparison = transition.get("one_step_comparison", {})
    if comparison:
        w("Transition model against its empirical baseline (one month ahead):")
        w("")
        w("| Model | Log-loss | Macro-F1 | AUC (Current) | AUC (30DPD) |")
        w("|---|---|---|---|---|")
        for label in ("empirical baseline", "covariate transition model"):
            def g(field):
                return comparison.get(field, {}).get(label, "-")
            w("| {} | {} | {} | {} | {} |".format(
                label, g("log_loss"), g("macro_f1"),
                g("auc_Current"), g("auc_30DPD")))
        w("")

    cross = transition.get("crosscheck_12m_default", {})
    if cross:
        w("**Independent cross-check.** The 12-month cumulative default "
          "probability read off the transition chain, scored against "
          "`next_12m_default_flag` — a label the chain never sees:")
        w("")
        w("| n | Observed rate | Predicted rate | ROC-AUC | Brier |")
        w("|---|---|---|---|---|")
        w("| {:,} | {:.2%} | {:.2%} | {} | {} |".format(
            cross.get("n", 0), cross.get("observed_rate", 0),
            cross.get("predicted_rate", 0), cross.get("roc_auc", "-"),
            round(cross.get("brier", 0), 6)))
        w("")
        w("Two independently constructed estimators agreeing on the same "
          "quantity is the strongest single piece of evidence in this "
          "project that the modelling is sound.")
        w("")

    # ------------------------------------------------------------ 7
    w("## 7. Leakage controls")
    w("")
    w("- **Target columns are excluded from every feature set.** "
      "`next_state` would predict `next_3m_delinquency_flag` almost "
      "perfectly and mean nothing.")
    w("- **`loss_severity_band` is dropped**, not imputed: it is 99.95% "
      "missing *and* a post-outcome field.")
    w("- **Identifiers and raw dates are excluded** so a tree cannot "
      "memorise individual loans or encode position in the panel.")
    w("- **History features use expanding windows within each loan**, "
      "never centred or ungrouped. A regression test truncates the future "
      "of a fixture whose tail is deliberately catastrophic and asserts "
      "the earlier rows are unchanged.")
    w("- **Purge gaps** prevent forward-looking labels straddling the "
      "split boundary; **label-maturity filtering** removes rows whose "
      "outcome window runs past the panel.")
    w("- **The anomaly detector is target-blind** — it never sees any "
      "target or the rule outputs, which is what makes its agreement with "
      "the rule engine independent evidence rather than a restatement.")
    w("- **Preprocessing is fitted inside the training fold only**, via "
      "sklearn Pipelines.")
    w("")

    # ------------------------------------------------------------ 8
    w("## 8. Known failure modes")
    w("")
    w("These are measured, not anticipated. Each is reproducible from the "
      "artifact named.")
    w("")

    prepay = supervised.get("next_12m_prepayment_flag")
    if prepay:
        metrics = pd.DataFrame(prepay["metrics"])
        final = (metrics[metrics.calibrated] if metrics.calibrated.any()
                 else metrics).sort_values("pr_auc", ascending=False).iloc[0]
        w("**Prepayment is close to unpredictable out of time.** ROC-AUC "
          "{}, and recall at 50% precision is {} — meaning a "
          "precision-controlled prepayment review queue cannot be operated "
          "at all on this data. The `rate_incentive` feature is strongly "
          "predictive *within* a period (prepayment rises from 6.3% to "
          "30.2% across training-window incentive quintiles) but the "
          "relationship does not transfer: the same spread collapses to "
          "1.6x in the test window as the rate environment shifts. The "
          "drift analysis had flagged `interest_rate` as the single "
          "largest source of train/test separation before the model was "
          "trained. A period-relative version of the feature recovered "
          "only 0.561 to 0.575 ROC-AUC. *(`model_performance_report.md`, "
          "`data_intelligence_report.md`)*".format(
              final["roc_auc"], final.get("recall_at_p50", "-")))
        w("")

    w("**The delinquency models largely read current delinquency state.** "
      "At the 50%-precision operating point, false positives carry "
      "`days_past_due` of 12.4 against 0.13 for true negatives (+1.13 sd) "
      "— loans already delinquent that then cure. False negatives carry "
      "0.0 against 45.8 for true positives (-2.75 sd) — clean loans taking "
      "a first slip. The model is strong on \"already sliding keeps "
      "sliding\" and close to blind on \"clean loan, first miss\", which "
      "is the case a reviewer most wants flagged. "
      "*(`explainability_report.md`)*")
    w("")

    default = supervised.get("next_12m_default_flag")
    if default:
        w("**Engineered features add nothing to 12-month default.** The "
          "logistic baseline and the gradient-boosted model tie, and the "
          "baseline is champion. With roughly 66 events in the evaluation "
          "window there is not enough signal to pay for the extra "
          "capacity. The target still has the best ROC-AUC and the highest "
          "lift of the four, but any conclusion drawn from it rests on "
          "very few events. *(`model_performance_report.md`)*")
        w("")

    w("**Predictions are unstable across training periods.** Refitting on "
      "expanding time windows and scoring the same rows, the spread "
      "between fold models exceeds the prediction itself on 67.5% of rows. "
      "`model_confidence` in the submission reports this per record. "
      "*(`explainability_report.md`, `data/derived/uncertainty.csv`)*")
    w("")

    w("**Rule-engine recall is measured on the data the rules were written "
      "against.** The engine resolves 100% of labelled exceptions at 98.2% "
      "precision, but the invariants were chosen after inspecting this "
      "panel, so that figure is closer to a fit than a forecast. What "
      "transfers to a different data pack is the mechanism — declare the "
      "invariant, measure precision and recall, promote a check when it "
      "beats a model — not the number. *(`anomaly_report.md`)*")
    w("")

    w("**No cure transitions exist in this synthetic pack.** Zero "
      "observed transitions out of 60DPD or 90DPD back toward current. "
      "Real servicing data has substantial cure rates, so the transition "
      "matrix is optimistic about severity progression. The state machine "
      "is declared generally rather than narrowed to what was observed, so "
      "cures are representable if a real pack contains them. "
      "*(`survival_report.md`)*")
    w("")

    # ------------------------------------------------------------ 9
    w("## 9. Limitations")
    w("")
    w("- The dataset is synthetic and roughly 5x smaller than the "
      "challenge specification suggests (47,883 rows against 250,000+). "
      "Rare-event targets are thin: 12-month default has 49 state "
      "transitions in the entire panel.")
    w("- Metrics carry no confidence intervals. At these event counts the "
      "uncertainty around a PR-AUC is material and is not quantified.")
    w("- Forward simulation holds credit band, LTV, state and servicer "
      "fixed, modelling only mechanical evolution (ageing, scheduled "
      "amortisation). Borrower re-underwriting and servicing transfers are "
      "not modelled.")
    w("- Scenario multipliers are applied as declared in "
      "`macro_scenarios.csv`. The engine propagates them faithfully; it "
      "does not validate that they are plausible.")
    w("- No fairness analysis has been run. State and credit band are used "
      "as features, and their disparate impact is unmeasured.")
    w("")

    # ------------------------------------------------------------ 10
    w("## 10. Reproducibility")
    w("")
    w("Fixed seed ({}) throughout. Each phase has one runner that "
      "regenerates its artifacts from the data pack:".format(RANDOM_SEED))
    w("")
    w("```bash")
    for script in ("run_data_intelligence", "run_transition_engine",
                   "run_supervised_models", "run_anomaly_detection",
                   "run_explainability", "run_llm_review",
                   "build_submission", "build_model_card"):
        w("python -m scripts.{}".format(script))
    w("```")
    w("")
    w("`pytest` covers the failure modes that do not announce themselves: "
      "leakage in history features, probability columns collapsing under "
      "calibration, guardrails silently weakening, rules leaking across "
      "loan boundaries.")
    w("")

    path = DOCS_DIR / "model_card.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote {} ({:,} bytes)".format(path, path.stat().st_size))


if __name__ == "__main__":
    main()
