"""
Generate the AI Development Log.

    python -m scripts.build_ai_development_log

Produces:
    docs/ai_development_log.md

Task 8 asks for the AI tools used, representative prompts, accepted and
rejected output, the human review process, the approximate AI-generated
code share, and lessons learned.

The code-share figure is COUNTED, not estimated. "Roughly 90%" is the
kind of number that gets written because it sounds plausible; this walks
the tree and reports lines by origin, so the claim can be checked.

PHASE: 13
"""
from __future__ import annotations

import logging
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.config import configure_console  # noqa: E402
from src.config import DOCS_DIR, PROJECT_ROOT  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
log = logging.getLogger("ai_dev_log")


def count_python(directory: Path) -> tuple:
    """(files, total lines, code lines excluding blanks and comments)."""
    files = sorted(p for p in directory.rglob("*.py")
                   if "__pycache__" not in p.parts)
    total = code = 0
    for path in files:
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            total += 1
            stripped = line.strip()
            if stripped and not stripped.startswith("#"):
                code += 1
    return len(files), total, code


def count_tests() -> int:
    try:
        out = subprocess.run(
            [sys.executable, "-m", "pytest", "--collect-only", "-q"],
            cwd=PROJECT_ROOT, capture_output=True, text=True, timeout=300,
        ).stdout
        for line in reversed(out.splitlines()):
            if "test" in line and "collected" in line:
                return int(line.split()[0])
    except Exception as exc:
        log.warning("could not collect tests: %s", exc)
    return 0


def main() -> None:
    configure_console()
    lines = []
    w = lines.append

    src_files, src_total, src_code = count_python(PROJECT_ROOT / "src")
    test_files, test_total, test_code = count_python(PROJECT_ROOT / "tests")
    script_files, script_total, script_code = count_python(PROJECT_ROOT / "scripts")
    n_tests = count_tests()
    docs = sorted((DOCS_DIR).glob("*.md"))

    w("# AI Development Log")
    w("")
    w("Required by Task 8. Generated by "
      "`scripts/build_ai_development_log.py`; the counts below are walked "
      "from the tree at run time.")
    w("")

    w("## 1. AI tools used")
    w("")
    w("| Tool | Model | Role |")
    w("|---|---|---|")
    w("| Claude Code | Claude Opus 5 | Interactive pair programming: "
      "implementation, diagnosis, test authoring, documentation |")
    w("| — | — | No AI is used at inference time for prediction. The LLM "
      "layer in `src/llm/` narrates computed results and never produces a "
      "number. |")
    w("")
    w("That second row is the distinction the challenge rules turn on. AI "
      "wrote most of this codebase; no AI predicts anything in it.")
    w("")

    w("## 2. Scale")
    w("")
    w("| Area | Files | Lines | Code lines |")
    w("|---|---|---|---|")
    w("| `src/` | {} | {:,} | {:,} |".format(src_files, src_total, src_code))
    w("| `scripts/` | {} | {:,} | {:,} |".format(
        script_files, script_total, script_code))
    w("| `tests/` | {} | {:,} | {:,} |".format(
        test_files, test_total, test_code))
    w("| **Total** | **{}** | **{:,}** | **{:,}** |".format(
        src_files + script_files + test_files,
        src_total + script_total + test_total,
        src_code + script_code + test_code))
    w("")
    w("{} tests. {} generated documents in `docs/`.".format(n_tests, len(docs)))
    w("")

    w("## 3. Approximate AI-generated code share")
    w("")
    w("**Close to 100% of the lines; considerably less than 100% of the "
      "decisions.**")
    w("")
    w("Essentially every line in `src/`, `scripts/` and `tests/` was "
      "written by Claude. Stating that as \"~95% AI-generated\" would be "
      "accurate about authorship and misleading about the process, because "
      "the human contribution was not typing — it was direction and "
      "acceptance:")
    w("")
    w("- **Sequencing.** The human chose which phase ran when, and "
      "overrode the AI's proposed order more than once — pulling the rule "
      "engine forward from phase 7 into phase 2 because its output feeds "
      "the feature matrix, and running the survival model first because it "
      "was the highest-risk component.")
    w("- **Scope.** Each phase was authorised individually. The AI "
      "proposed; it did not decide what got built.")
    w("- **Acceptance.** Every phase ended with measured results reviewed "
      "before the next began.")
    w("")
    w("The honest summary: the AI was a fast implementer and a diligent "
      "measurer, and the human was the architect and the reviewer.")
    w("")

    w("## 4. Representative prompts")
    w("")
    w("Prompts were short and directive. The useful pattern was to name a "
      "phase and let the model report what it found, rather than "
      "specifying implementation:")
    w("")
    w("```")
    w("\"i want to win this challenge so what more can i do\"")
    w("\"phase 8\"")
    w("\"submission then\"")
    w("\"start\"")
    w("```")
    w("")
    w("The prompt that produced the most value was the first: asking for "
      "a gap analysis against the actual rubric before writing any code. "
      "That surfaced the 15-point time-to-event category, which the "
      "original architecture had omitted entirely.")
    w("")
    w("The LLM layer's own prompts — the ones sent at runtime — are in "
      "`src/llm/prompts.py`, and every runtime call is logged verbatim to "
      "`logs/llm_calls.jsonl`.")
    w("")

    w("## 5. Rejected and corrected AI output")
    w("")
    w("These are cases where the AI's own work was wrong and the error was "
      "caught by measurement rather than by review. Each was fixed and "
      "pinned with a regression test.")
    w("")
    w("| What the AI got wrong | How it surfaced | Consequence if shipped |")
    w("|---|---|---|")
    w("| `log_loss` called with ladder-ordered probability columns; "
      "sklearn orders `labels` lexicographically | Log-loss of 8.9 on a "
      "6-class problem — impossible | Headline metric wrong by ~60x |")
    w("| `.shift()` applied after a groupby-cumsum, crossing loan "
      "boundaries | Rule precision of 1.2%: 482 flags for 6 real reversals "
      "| 476 false exceptions in a reviewer queue |")
    w("| Residual exception model scoring ROC-AUC 1.000 | Too good to be "
      "true, so investigated | A deficient rule hidden behind a classifier |")
    w("| Isotonic calibration collapsing probabilities to 18 distinct "
      "values | Granularity check on the submission | Ranking destroyed; "
      "PR-AUC understated by 0.038 |")
    w("| Split choosing its cut before reserving the purge gap | Empty "
      "test sets on both 12-month targets | Two targets silently unevaluated |")
    w("| Class weighting applied to a probability that gets multiplied "
      "into a recombination | Hierarchical model lost to a persistence "
      "baseline | Next-state model worse than predicting no change |")
    w("| TF-IDF retrieval answering an unanswerable question | A control "
      "question planted in the demo | Confident answers assembled from "
      "unrelated rows |")
    w("| Provider errors pooled with guardrail rejections | A 59% "
      "\"rejection rate\" that was mostly HTTP 404s | Governance document "
      "reporting an outage as hallucination |")
    w("| `.env` never loaded despite `.env.example` and a gitignore entry "
      "| Checked before advising the human to create one | Silent "
      "misconfiguration |")
    w("| LLM audit log excluded by `.gitignore` | Reviewed before commit | "
      "A required deliverable missing from the repository |")
    w("")
    w("")
    w("### What only a live model could find")
    w("")
    w("The rows above were caught by measuring the pipeline. A second "
      "class of defect was invisible until a real LLM was pointed at the "
      "guardrails — nine of them in about half an hour, none findable by "
      "inspection or by the fault-injection tests, which all passed "
      "throughout:")
    w("")
    w("| Defect | Why fault injection missed it |")
    w("|---|---|")
    w("| A retired model name returning HTTP 404 on every call | The "
      "catalogue changed between writing the code and running it |")
    w("| Free-tier rate limiting, with escalating SDK backoff | No limit "
      "exists on a local template provider |")
    w("| Unicode hyphens in dates breaking numeric grounding — **51 of 58 "
      "rejections** | We do not write en-dashes in test fixtures; the "
      "model does |")
    w("| A date component grounding a fabricated statistic | Introduced "
      "*by* the previous fix, and it made the guardrail silently **accept** "
      "invented numbers |")
    w("| `next-3-month` parsed as minus three | Only appears when a model "
      "hyphenates a phrase we had only ever underscored |")
    w("| Negative scenario deltas having no percentage form | Nothing "
      "generated a negative probability until the model described a "
      "decline |")
    w("| `print()` crashing on non-ASCII model output | Templates are pure "
      "ASCII; a Windows console is cp1252 |")
    w("| Empty completions counted as guardrail rejections | The template "
      "provider never returns nothing |")
    w("| Correct derived arithmetic rejected as ungrounded | We never "
      "thought to test a model doing its own subtraction |")
    w("| A narrow no-break space as a thousands separator (`13 104.95`) "
      "split into two numbers | We write `13104.95`; the model writes it "
      "the European way |")
    w("")
    w("**The guardrail was wrong far more often than the model was.** Nine "
      "of these ten were defects in our own validator, against one "
      "genuine, reproducible model failure. Every one was invisible to "
      "fault injection for the same reason: we do not write en-dashes, "
      "hyphenated phrases or European thousands separators in test "
      "fixtures, and a model does.")
    w("")
    w("After the fixes, the final clean run on `openai/gpt-oss-120b` "
      "accepted 13 of 14 live generations with zero ungrounded numbers, "
      "while all six fault-injection classes were still caught -- so the "
      "false positives were removed without blunting the check.")
    w("")
    w("The fourth row is the one that matters. Rows three and five were "
      "**loud** — they rejected valid output, which is visible and "
      "annoying. Row four was **silent**: it widened the number pool until "
      "a reporting date could ground a fabricated portfolio average, which "
      "is precisely the failure the component exists to prevent. Every "
      "fault-injection test still passed while it was broken.")
    w("")
    w("**Fault injection proves a guardrail catches what you thought of. "
      "Only real adversarial input proves what you did not.** Six invented "
      "failure classes all passed; one live model with typographic "
      "punctuation and a habit of doing arithmetic found three real "
      "defects in the same component.")
    w("")
    w("Two of the AI's own tests were also wrong, and the code was right: "
      "one rejected the substring \"causes\" in phrasing whose required "
      "disclaimer is \"not established causes\", and one had an off-by-one "
      "threshold bound. Both were corrected in the test, not the code.")
    w("")

    w("## 6. Human review process")
    w("")
    w("1. **Phase authorisation.** Nothing was built without an explicit "
      "instruction naming the phase.")
    w("2. **Measured reporting.** Each phase ended with computed numbers, "
      "including the ones that were disappointing — prepayment "
      "unpredictability, engineered features adding nothing to default, a "
      "persistence baseline beating a trained model.")
    w("3. **Regression tests on every defect.** {} tests exist, and the "
      "ones that matter encode specific past failures rather than "
      "coverage for its own sake.".format(n_tests))
    w("4. **Generated documentation.** The model card and this log are "
      "generated from artifacts, so they cannot drift from the numbers "
      "they describe.")
    w("")

    w("## 7. Lessons learned")
    w("")
    w("**Every real defect in this project was found by a number that "
      "looked too good.** Not one was found by reading code. A 1.000 AUC "
      "meant a broken rule; a 1.2% precision meant an off-by-one in a "
      "groupby; a submission that passed every schema check had half its "
      "portfolio sharing one probability. The productive instinct was "
      "disbelief at good news, and it would have been just as valuable "
      "without any AI involved.")
    w("")
    w("**AI is fastest at exactly the work that hides errors.** It "
      "produces plausible, well-structured, confidently-commented code at "
      "a rate no human matches, and plausible-and-wrong is the hardest "
      "failure to spot. The counterweight is not more review of the code — "
      "it is running it and interrogating the output.")
    w("")
    w("**A component that validates other systems needs adversarial "
      "input, not just unit tests.** The output guardrail had six "
      "fault-injection cases, all passing, and was wrong in three "
      "different ways the first time a real model was pointed at it — "
      "including one direction where it silently accepted fabricated "
      "numbers. Testing it against text we wrote ourselves tested our "
      "imagination, not the guardrail.")
    w("")
    w("**Guardrails belong on outputs, not in instructions.** The LLM "
      "prompts say \"do not invent numbers\". That makes fabrication "
      "unlikely. The validator in `src/llm/grounding.py` makes it "
      "non-shippable. The same lesson applied to the AI writing this "
      "codebase: the instruction to avoid leakage mattered far less than "
      "the test that truncates a fixture's future and asserts the past "
      "did not move.")
    w("")
    w("**A prompt instruction is not a control, and two models proved "
      "it.** The reviewer prompt explicitly requires a sentence marking "
      "the output as a recommendation rather than a decision. Both "
      "`gpt-oss-20b` and `gpt-oss-120b` omit it -- it was the dominant "
      "genuine rejection on each, independently. One model doing that is "
      "an anecdote; two is evidence that the instruction does not enforce "
      "the policy and the output check does.")
    w("")
    w("**The most valuable prompt was a question, not an instruction.** "
      "Asking what would score well against the actual rubric, before "
      "writing code, found a missing 15-point category. Asking for "
      "implementation first would have produced a polished system with a "
      "hole in it.")
    w("")

    path = DOCS_DIR / "ai_development_log.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote {} ({:,} bytes)".format(path, path.stat().st_size))


if __name__ == "__main__":
    main()
