"""
Anomaly and exception detection pass.

    python -m scripts.run_anomaly_detection

Produces:
    docs/anomaly_report.md                 the graded deliverable
    data/derived/reviewer_examples.csv     25 curated, reviewer-ready cases
    data/derived/exception_output.csv      per-record probability + type
    models/anomaly_detector.joblib         fitted IsolationForest + reference

Depends on phase 2 (rules, reconciliation) and phase 3 (features).

PHASE: 7
"""
from __future__ import annotations

import logging
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.anomaly.detector import (  # noqa: E402
    anomaly_reasons_frame,
    detect_anomalies,
    explain_anomaly,
    phrase_reason,
)
from src.anomaly.exception_model import (  # noqa: E402
    combined_exception_output,
    rule_covered_mask,
    train_exception_models,
)
from src.anomaly.rules import evaluate_rules  # noqa: E402
from src.config import configure_console  # noqa: E402
from src.config import DATA_DIR, DOCS_DIR, LOAN_ID_COLUMN, MODELS_DIR, TIME_COLUMN  # noqa: E402
from src.data.loader import attach_static_attributes, load_data_pack, sort_panel  # noqa: E402
from src.data.profiler import record_quality_scores  # noqa: E402
from src.data.reconciliation import reconcile  # noqa: E402
from src.explainability.labels import describe_exception, describe_rule  # noqa: E402
from src.features.engineering import engineer_features  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
log = logging.getLogger("anomaly")

DERIVED_DIR = DATA_DIR / "derived"
N_REVIEWER_EXAMPLES = 25


def main() -> None:
    configure_console()
    DERIVED_DIR.mkdir(parents=True, exist_ok=True)
    report: list = []

    def emit(text: str = "") -> None:
        report.append(text)

    def block(title: str, body: str) -> None:
        print("\n" + "=" * 72)
        print(title)
        print("=" * 72)
        print(body)
        emit()
        emit("## " + title)
        emit()
        emit("```")
        emit(body)
        emit("```")

    # ------------------------------------------------------------ build
    pack = load_data_pack(DATA_DIR)
    panel = sort_panel(attach_static_attributes(pack.train, pack.static))
    recon = reconcile(panel, pack.servicer_updates)
    engine = evaluate_rules(panel, reconciliation=recon.record_flags)
    quality = record_quality_scores(panel, engine.severity_score(), recon.record_flags)
    features, _ = engineer_features(
        panel, engine.flags, recon.record_flags, quality["data_quality_score"]
    )

    emit("# Anomaly and Exception Report")
    emit()
    emit("Generated by `scripts/run_anomaly_detection.py`. Every figure is "
         "computed at run time.")
    emit()
    emit("Language note: this layer reports records as **unusual and "
         "requiring review**. It never asserts fraud or misconduct. An "
         "Isolation Forest observes that a record is statistically unlike "
         "its peers; it does not know why, and that distinction matters to "
         "whoever has to act on the flag.")

    # -------------------------------------------------- 1. unsupervised
    anomaly = detect_anomalies(features)
    block("1. Unsupervised anomaly detection (Isolation Forest)", anomaly.summary())
    emit()
    emit("The detector is target-blind: `exception_required`, "
         "`exception_type`, every performance target, and the rule outputs "
         "are all excluded from its feature set. Otherwise it would become "
         "a laundered copy of the rule engine, and its agreement with the "
         "rules would stop being evidence of anything.")

    truth = features["exception_required"].fillna(0).astype(int)
    from sklearn.metrics import average_precision_score, roc_auc_score

    body = "\n".join([
        "anomaly score vs exception_required (the detector never saw it)",
        "  ROC-AUC : {:.4f}".format(roc_auc_score(truth, anomaly.scores)),
        "  PR-AUC  : {:.4f}  (base rate {:.4f})".format(
            average_precision_score(truth, anomaly.scores), truth.mean()),
        "",
        "exception rate by anomaly-score decile",
    ])
    dec = pd.qcut(anomaly.scores, 10, labels=False, duplicates="drop")
    tbl = (pd.DataFrame({"decile": dec + 1, "exception": truth})
           .groupby("decile").agg(n=("exception", "size"),
                                  exception_rate=("exception", "mean")).round(4))
    block("2. Does the unsupervised score track real exceptions?",
          body + "\n" + tbl.to_string())

    # ------------------------------------------------------ 2. coverage
    exc = train_exception_models(features, engine.flags, anomaly.scores)
    block("3. Rule coverage and the residual", exc.coverage.to_string(index=False))
    for note in exc.notes:
        emit()
        emit("> {}".format(note))

    emit()
    emit("**A caveat that belongs next to that 100%.** These rules were "
         "written after inspecting this panel, so their measured recall is "
         "optimistic by construction -- it is closer to a fit than to a "
         "forecast. What transfers to the organizer's real pack is the "
         "*mechanism* (declare the invariant, measure precision and recall "
         "against the labels, promote a check into the engine when it beats "
         "a model), not the specific number. Every rule states the invariant "
         "it enforces, so each can be re-validated on new data in isolation.")
    emit()
    emit("The `balance_within_original` rule is the clearest example of that "
         "mechanism working. The residual model initially scored ROC-AUC "
         "1.000 on the exceptions the declared rules missed. A perfect score "
         "on nine positives is not a discovery, it is a symptom: the "
         "month-over-month balance rule cannot fire on a loan's first "
         "observed row, because there is no previous row to compare. The "
         "profiler's cross-column check had already found the better "
         "invariant. Promoting it into the rule engine took "
         "balance_inconsistency recall from 94.3% to 100% and removed the "
         "need for the model entirely -- an auditable check in place of a "
         "classifier that was quietly rediscovering it.")

    if len(exc.residual_metrics):
        block("4. Residual exception model (rows no rule flags)",
              exc.residual_metrics.to_string(index=False))
        emit()
        emit("These metrics describe the model's OWN contribution. Training "
             "on the full population with the rule flags as features would "
             "have produced a much prettier number that simply restated the "
             "rule engine's 98% precision as the model's.")
    if len(exc.type_metrics):
        block("5. Residual exception-type classifier",
              exc.type_metrics.to_string(index=False))

    # ------------------------------------------------------- 3. combined
    combined = combined_exception_output(features, engine.flags, anomaly, exc)
    mix = combined["decided_by"].value_counts().rename("n_records").to_frame()
    mix["pct"] = (100 * mix.n_records / len(combined)).round(2)
    block("6. How each record was decided", mix.to_string())
    emit()
    emit("`decided_by` travels with every record so a reviewer never has to "
         "guess whether they are looking at a rule citation or a model "
         "score. A rule that fires is a fact about the record and outranks "
         "any probability.")

    # ------------------------------------- 4. reviewer-ready examples
    covered = rule_covered_mask(engine.flags)
    ranked = combined.assign(
        rule_hit=covered,
        n_rules=engine.flags.sum(axis=1),
    ).sort_values(["exception_probability", "anomaly_score"], ascending=False)

    # Deliberately mixed: rule-resolved cases AND high-anomaly cases no
    # rule caught. A reviewer queue of only rule hits teaches nothing about
    # what the unsupervised layer adds.
    rule_cases = ranked[ranked.rule_hit].head(15).index
    model_cases = ranked[~ranked.rule_hit].head(10).index
    chosen = list(rule_cases) + list(model_cases)

    population = features[anomaly.feature_columns]
    rows = []
    for idx in chosen:
        row = features.loc[idx]
        fired = [r for r in engine.flags.columns if bool(engine.flags.loc[idx, r])]
        drivers = explain_anomaly(row, anomaly.reference, population, top_n=3)
        rows.append({
            "loan_id": row[LOAN_ID_COLUMN],
            "reporting_month": str(pd.Timestamp(row[TIME_COLUMN]).date()),
            "status": row.get("current_status"),
            "decided_by": combined.loc[idx, "decided_by"],
            "exception_probability": round(
                float(combined.loc[idx, "exception_probability"]), 4),
            "anomaly_score": round(float(anomaly.scores.loc[idx]), 4),
            "predicted_type": describe_exception(
                combined.loc[idx, "exception_type_pred"]),
            "rules_broken": "; ".join(describe_rule(r) for r in fired) or "none",
            "why_unusual": " | ".join(phrase_reason(d) for d in drivers)
            or "no single field is individually extreme; unusual in combination",
            "actual_exception_type": row.get("exception_type", "unknown"),
        })
    examples = pd.DataFrame(rows)
    examples.to_csv(DERIVED_DIR / "reviewer_examples.csv", index=False)

    emit()
    emit("## 7. Reviewer-ready examples")
    emit()
    emit("{} cases: the {} highest-confidence rule-resolved records, plus "
         "the {} most unusual records that NO rule flagged. The second group "
         "is the point -- it is what the unsupervised layer contributes, and "
         "a queue made only of rule hits would hide it.".format(
             len(examples), len(rule_cases), len(model_cases)))
    emit()
    for _, r in examples.iterrows():
        emit("**{} · {}** — {} (score {:.3f}, decided by {})".format(
            r.loan_id, r.reporting_month, r.predicted_type,
            r.exception_probability, r.decided_by))
        emit()
        emit("- Status: {}".format(r.status))
        emit("- Rules broken: {}".format(r.rules_broken))
        emit("- Why unusual: {}".format(r.why_unusual))
        emit("- Label in the data: {}".format(r.actual_exception_type))
        emit()

    print("\n" + "=" * 72)
    print("7. Reviewer-ready examples")
    print("=" * 72)
    print(examples[["loan_id", "reporting_month", "decided_by",
                    "exception_probability", "anomaly_score",
                    "actual_exception_type"]].to_string(index=False))

    # --------------------------------------------------------- persist
    combined.assign(
        loan_id=features[LOAN_ID_COLUMN].values,
        reporting_month=features[TIME_COLUMN].values,
    ).to_csv(DERIVED_DIR / "exception_output.csv", index=False)

    joblib.dump(
        {"model": anomaly.model, "reference": anomaly.reference,
         "feature_columns": anomaly.feature_columns,
         "residual_model": exc.residual_model, "type_model": exc.type_model,
         "residual_feature_cols": exc.feature_cols},
        MODELS_DIR / "anomaly_detector.joblib",
    )
    (DOCS_DIR / "anomaly_report.md").write_text(
        "\n".join(report) + "\n", encoding="utf-8"
    )
    print("\nWrote docs/anomaly_report.md")
    print("Wrote data/derived/reviewer_examples.csv ({} cases)".format(len(examples)))
    print("Wrote data/derived/exception_output.csv")
    print("Wrote models/anomaly_detector.joblib")


if __name__ == "__main__":
    main()
