"""
LLM reviewer copilot demo and governance pass.

    python -m scripts.run_llm_review

Produces:
    docs/llm_copilot_report.md      the demo deliverable
    docs/rejected_llm_outputs.md    required evidence of caught failures
    logs/llm_calls.jsonl            the audit trail (appended, not replaced)

Runs with no API key configured. The deterministic provider renders the
same grounded context objects, so the copilot is fully functional offline
and a live demo cannot fail on an expired key or a rate limit.

PHASE: 10
"""
from __future__ import annotations

import json
import logging
import sys
import warnings
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

warnings.filterwarnings("ignore", category=FutureWarning)

from src.anomaly.detector import detect_anomalies, explain_anomaly  # noqa: E402
from src.anomaly.exception_model import rule_assigned_type, rule_covered_mask  # noqa: E402
from src.anomaly.rules import evaluate_rules  # noqa: E402
from src.config import configure_console  # noqa: E402
from src.config import DATA_DIR, DOCS_DIR, LOGS_DIR  # noqa: E402
from src.data.loader import attach_static_attributes, load_data_pack, sort_panel  # noqa: E402
from src.data.profiler import record_quality_scores  # noqa: E402
from src.data.reconciliation import reconcile  # noqa: E402
from src.explainability.labels import describe_rule  # noqa: E402
from src.explainability.shap_explainer import explain_model, explain_one  # noqa: E402
from src.features.engineering import engineer_features  # noqa: E402
from src.llm.grounding import validate_output  # noqa: E402
from src.llm.llm_logging import log_llm_call, read_log, summarise_log  # noqa: E402
from src.llm.provider import FaultInjectionProvider, get_provider  # noqa: E402
from src.llm.retrieval import DocumentationRetriever, answer_from_documentation  # noqa: E402
from src.llm.reviewer import (  # noqa: E402
    LOG_PATH, build_context, generate_reviewer_note, generate_scenario_summary,
)
from src.models.train import BINARY_TARGETS, train_binary_target  # noqa: E402
from src.models.validation import time_aware_split  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
log = logging.getLogger("llm_review")

N_DEMO_LOANS = 12

TERM_QUESTIONS = [
    "What does ltv_band mean?",
    "What is days_past_due?",
    "What does the balance_non_increasing rule check?",
    "What is loss_severity_band?",
    "What is the borrower's favourite colour?",
]


def main() -> None:
    configure_console()
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    report, rejected_doc = [], []

    def emit(text: str = "") -> None:
        report.append(text)

    def block(title: str, body: str) -> None:
        print("\n" + "=" * 72)
        print(title)
        print("=" * 72)
        print(body)
        emit()
        emit("## " + title)
        emit()
        emit("```")
        emit(body)
        emit("```")

    provider = get_provider()
    is_live = provider.name not in ("template",)

    emit("# LLM Reviewer Copilot")
    emit()
    emit("Generated by `scripts/run_llm_review.py`.")
    emit()
    emit("Active provider: **{}** (`{}`).".format(provider.name, provider.model))
    emit()
    if not is_live:
        emit("No API credentials are configured, so the deterministic "
             "provider is serving every call. It renders the same grounded "
             "context objects through fixed templates, which means the "
             "copilot is fully functional offline and a live demo cannot "
             "fail on an expired key or a rate limit. Setting `LLM_PROVIDER` "
             "and a key switches the provider without changing anything "
             "else -- the guardrails, the audit log and the fallback are "
             "identical on both paths.")

    # ------------------------------------------------------------ data
    pack = load_data_pack(DATA_DIR)
    panel = sort_panel(attach_static_attributes(pack.train, pack.static))
    recon = reconcile(panel, pack.servicer_updates)
    engine = evaluate_rules(panel, reconciliation=recon.record_flags)
    quality = record_quality_scores(panel, engine.severity_score(), recon.record_flags)
    features, _ = engineer_features(
        panel, engine.flags, recon.record_flags, quality["data_quality_score"]
    )

    target = "next_3m_delinquency_flag"
    result = train_binary_target(features, target)
    model, cols = result.models[result.champion]
    split = time_aware_split(
        features[features[target].notna()], purge_months=3, test_fraction=0.2
    )
    shap_result = explain_model(model, split.test, cols, sample=1500)
    anomaly = detect_anomalies(features)
    covered = rule_covered_mask(engine.flags)
    types = rule_assigned_type(engine.flags)

    # ------------------------------------------------- reviewer notes
    probs = pd.Series(
        model.predict_proba(split.test[cols])[:, 1], index=split.test.index
    )
    if result.calibration is not None:
        probs = pd.Series(result.calibration.apply(probs.values), index=probs.index)

    # A deliberately mixed queue: the riskiest records, plus rule-flagged
    # ones, so the notes exercise both the risk and the exception paths.
    risky = probs.nlargest(N_DEMO_LOANS // 2).index
    flagged = [i for i in split.test.index if covered.get(i, False)][:N_DEMO_LOANS // 2]
    chosen = list(dict.fromkeys(list(risky) + list(flagged)))

    population = features[anomaly.feature_columns]
    generated = []
    for idx in chosen:
        row = features.loc[idx]
        local = explain_one(model, row, cols, shap_result, top_n=4)

        context = build_context(
            row,
            predictions={"next_3m_delinquency": float(probs.loc[idx])},
            drivers=local,
            anomaly={
                "score": float(anomaly.scores.loc[idx]),
                "drivers": explain_anomaly(row, anomaly.reference, population, 3),
            },
            exception={
                "required": bool(covered.get(idx, False)),
                "type": types.get(idx, "none"),
                "decided_by": "rule" if covered.get(idx, False) else "model score",
                "rules_broken": [describe_rule(c) for c in engine.flags.columns
                                 if bool(engine.flags.loc[idx, c])],
            },
        )
        note = generate_reviewer_note(context, provider=provider)
        generated.append({
            "loan_id": context["loan_id"],
            "reporting_month": context["reporting_month"],
            "probability": context["predictions"]["next_3m_delinquency"],
            "accepted": note.accepted,
            "fell_back": note.fell_back,
            "text": note.text,
        })

    emit()
    emit("## Reviewer notes")
    emit()
    emit("{} notes generated. Every one was validated against its own "
         "context before being shown.".format(len(generated)))
    for g in generated[:6]:
        emit()
        emit("**{} · {}** — model estimate {:.2%}".format(
            g["loan_id"], g["reporting_month"], g["probability"]))
        emit()
        emit("> " + g["text"])
    print("\nGenerated {} reviewer notes".format(len(generated)))

    # ------------------------------------------------ scenario summary
    curves = DATA_DIR / "derived" / "scenario_curves.csv"
    if curves.exists():
        df = pd.read_csv(curves)
        final = df[df.month == df.month.max()]
        # Include the deltas against base. The guardrail rejects numbers
        # that are not in the context, and on the first live run the model
        # correctly derived scenario differences (30.62 - 16.04 = 14.57)
        # and was rejected for it. The arithmetic was right that time. The
        # fix is not to start trusting LLM arithmetic -- it is to compute
        # the comparison the narrative obviously needs and hand it over,
        # so the model quotes rather than calculates.
        base_row = final[final.scenario == "base"]
        base_default = float(base_row.cif_default.iloc[0]) if len(base_row) else None
        base_prepaid = float(base_row.cif_prepaid.iloc[0]) if len(base_row) else None
        scenarios = []
        for r in final.itertuples():
            entry = {"scenario": r.scenario,
                     "default_12m": round(float(r.cif_default), 5),
                     "prepaid_12m": round(float(r.cif_prepaid), 5)}
            if base_default is not None:
                entry["default_change_vs_base"] = round(
                    float(r.cif_default) - base_default, 5)
                entry["prepaid_change_vs_base"] = round(
                    float(r.cif_prepaid) - base_prepaid, 5)
            scenarios.append(entry)
        scenario_context = {
            "horizon_months": int(df.month.max()),
            "scenarios": scenarios,
        }
        summary = generate_scenario_summary(scenario_context, provider=provider)
        block("Scenario summary", summary.text)

    # --------------------------------------------------- RAG lookups
    retriever = DocumentationRetriever()
    rows = []
    for question in TERM_QUESTIONS:
        answer = answer_from_documentation(question, retriever)
        rows.append({
            "question": question,
            "grounded": answer["grounded"],
            "answer": answer["answer"][:80],
            "sources": ", ".join(answer["citations"][:2]) or "-",
        })
    block("Documentation retrieval", pd.DataFrame(rows).to_string(
        index=False, max_colwidth=52))
    emit()
    emit("The last question is a control. Nothing in the corpus can answer "
         "it, and the retriever's relevance floor returns nothing rather "
         "than handing over its three least-irrelevant passages for a model "
         "to answer from confidently.")

    # ------------------------------------------- guardrail demonstration
    print("\n" + "=" * 72)
    print("Guardrail demonstration (fault injection)")
    print("=" * 72)

    rejected_doc.append("# Rejected and Corrected LLM Output")
    rejected_doc.append("")
    rejected_doc.append(
        "Required evidence for Task 7. Generated by "
        "`scripts/run_llm_review.py`; every verdict below is produced by "
        "`src/llm/grounding.py` at run time."
    )
    rejected_doc.append("")
    rejected_doc.append("## An honesty note about this document")
    rejected_doc.append("")
    rejected_doc.append(
        "No API credentials are configured for this run, so there is no "
        "real model output to show. Writing plausible text and captioning "
        "it \"the LLM said this\" would be fabricating evidence, which is "
        "the one thing this project refuses to do anywhere else."
    )
    rejected_doc.append("")
    rejected_doc.append(
        "So Section 1 uses a **fault-injection harness** "
        "(`FaultInjectionProvider`): text we wrote deliberately, containing "
        "the known failure modes, run through the real guardrail. It "
        "demonstrates that the control catches each class. It is labelled "
        "as fault injection in the audit log and here, and is never "
        "presented as something a model produced."
    )
    rejected_doc.append("")
    rejected_doc.append(
        "Section 2 carries rejections from live providers. It populates "
        "automatically from `logs/llm_calls.jsonl` whenever a key is "
        "configured, using the identical guardrail and the identical log."
    )
    rejected_doc.append("")
    rejected_doc.append("## Section 1 — guardrail demonstration (fault injection)")

    demo_context = generated and build_context(
        features.loc[chosen[0]],
        predictions={"next_3m_delinquency": float(probs.loc[chosen[0]])},
    ) or {"predictions": {"next_3m_delinquency": 0.0432}}

    caught = []
    for fault in FaultInjectionProvider.FAULTS:
        injector = FaultInjectionProvider(fault)
        text = injector.generate("")
        verdict = validate_output(text, demo_context)
        # Log the injected cases too. The audit trail is meant to be the
        # single record of every guardrail decision, so a demonstration
        # that bypasses it leaves the log reporting a 0% rejection rate
        # while the guardrail is visibly firing on screen. Tagged by
        # provider and task so these never blur into live generations.
        log_llm_call(
            LOG_PATH, injector.name, injector.model,
            "[fault injection: {}]".format(fault), text, 0.0,
            validation_result=verdict, context=demo_context,
            task="guardrail_demo", accepted=verdict.ok,
        )
        caught.append({
            "fault_class": fault,
            "caught": not verdict.ok,
            "failed_checks": ", ".join(verdict.failed_checks) or "-",
        })
        rejected_doc.append("")
        rejected_doc.append("### `{}`".format(fault))
        rejected_doc.append("")
        rejected_doc.append("*Injected text (written by us, not by a model):*")
        rejected_doc.append("")
        rejected_doc.append("> " + text)
        rejected_doc.append("")
        rejected_doc.append("*Guardrail verdict:*")
        rejected_doc.append("")
        rejected_doc.append("```")
        rejected_doc.append(verdict.describe())
        rejected_doc.append("```")
        rejected_doc.append("")
        rejected_doc.append("*Correction applied:* the generation is rejected, "
                            "retried once, and then replaced by the "
                            "deterministic rendering of the same context, "
                            "which is grounded by construction. The reviewer "
                            "sees a plainer note, never an unvalidated one.")

    caught_tbl = pd.DataFrame(caught)
    block("Guardrail demonstration (fault injection)",
          caught_tbl.to_string(index=False, max_colwidth=44))
    emit()
    emit("Every injected failure class was caught. The text above was "
         "written by us, not produced by a model -- see "
         "`docs/rejected_llm_outputs.md` for why that distinction is drawn "
         "explicitly rather than glossed.")

    # ------------------------------------------------ live rejections
    records = read_log(LOG_PATH)
    live_rejects = [
        r for r in records
        if not r.get("accepted", True)
        and r.get("provider") not in ("template", "fault-injection")
    ]
    rejected_doc.append("")
    rejected_doc.append("## Section 2 — rejections from a live provider")
    rejected_doc.append("")
    if live_rejects:
        rejected_doc.append(
            "{} live generations were rejected by the guardrail.".format(
                len(live_rejects)))
        for r in live_rejects[:10]:
            rejected_doc.append("")
            rejected_doc.append("### {} · {} · attempt {}".format(
                r["timestamp"], r.get("model"), r.get("attempt")))
            rejected_doc.append("")
            rejected_doc.append("> " + (r.get("output") or "")[:600])
            rejected_doc.append("")
            rejected_doc.append("Failed checks: {}".format(
                ", ".join(r.get("validation", {}).get("failed_checks", []))))
    else:
        rejected_doc.append(
            "No live-provider generations have been logged yet, because no "
            "API key is configured. This section fills itself from "
            "`logs/llm_calls.jsonl` on the first run with credentials "
            "present -- no code changes, no manual curation."
        )

    # ------------------------------------------------------ governance
    stats = summarise_log(LOG_PATH)
    block("Audit log summary", json.dumps(stats, indent=2))
    emit()
    emit("These numbers are computed from `logs/llm_calls.jsonl`, not "
         "asserted. Every call is logged -- accepted, rejected, errored and "
         "fallback alike -- because a log that records only successes "
         "cannot support the claim it exists to support.")

    (DOCS_DIR / "llm_copilot_report.md").write_text(
        "\n".join(report) + "\n", encoding="utf-8")
    (DOCS_DIR / "rejected_llm_outputs.md").write_text(
        "\n".join(rejected_doc) + "\n", encoding="utf-8")
    print("\nWrote docs/llm_copilot_report.md")
    print("Wrote docs/rejected_llm_outputs.md")
    print("Wrote logs/llm_calls.jsonl ({} total records)".format(
        stats.get("total_calls", 0)))


if __name__ == "__main__":
    main()
