"""
End-to-end supervised modelling pass.

    python -m scripts.run_supervised_models

Produces:
    docs/model_performance_report.md    the graded deliverable
    docs/feature_manifest.md            every engineered feature + rationale
    models/supervised/*.joblib          champion model per target
    models/supervised_metrics.json      metrics snapshot for the dashboard

Depends on phase 2: the rule flags, reconciliation flags and data-quality
scores it produces are features here, not just report content.

PHASE: 3-5
"""
from __future__ import annotations

import json
import logging
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.anomaly.rules import evaluate_rules  # noqa: E402
from src.config import configure_console  # noqa: E402
from src.config import DATA_DIR, DOCS_DIR, LOAN_ID_COLUMN, MODELS_DIR, TIME_COLUMN  # noqa: E402
from src.data.loader import attach_static_attributes, load_data_pack, sort_panel  # noqa: E402
from src.data.profiler import record_quality_scores  # noqa: E402
from src.data.reconciliation import reconcile  # noqa: E402
from src.features.engineering import engineer_features  # noqa: E402
from src.models.validation import (  # noqa: E402
    TARGET_HORIZON_MONTHS, time_aware_split,
)
from src.models.train import (  # noqa: E402
    BINARY_TARGETS,
    bootstrap_metric_intervals,
    mature_label_mask,
    predictability_ceiling,
    slice_metrics,
    train_binary_target,
    train_next_state,
)

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
log = logging.getLogger("supervised")

OUT_DIR = MODELS_DIR / "supervised"


def main() -> None:
    configure_console()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    report: list = []

    def emit(text: str = "") -> None:
        report.append(text)

    def block(title: str, body: str) -> None:
        print("\n" + "=" * 72)
        print(title)
        print("=" * 72)
        print(body)
        emit()
        emit("### " + title)
        emit()
        emit("```")
        emit(body)
        emit("```")

    # ------------------------------------------------------------- build
    pack = load_data_pack(DATA_DIR)
    panel = sort_panel(attach_static_attributes(pack.train, pack.static))

    recon = reconcile(panel, pack.servicer_updates)
    engine = evaluate_rules(panel, reconciliation=recon.record_flags)
    quality = record_quality_scores(panel, engine.severity_score(), recon.record_flags)

    features, manifest = engineer_features(
        panel,
        rule_flags=engine.flags,
        reconciliation_flags=recon.record_flags,
        quality_scores=quality["data_quality_score"],
        manifest_path=DOCS_DIR / "feature_manifest.md",
    )

    emit("# Model Performance Report")
    emit()
    emit("Generated by `scripts/run_supervised_models.py`. Every figure is "
         "computed at run time; nothing is hand-entered.")
    emit()
    emit("Feature matrix: {:,} rows x {} columns, of which {} are engineered "
         "(see `docs/feature_manifest.md`).".format(
             len(features), features.shape[1], len(manifest.entries)))

    block("Engineered features", manifest.to_frame()[
        ["feature", "family", "rationale"]
    ].to_string(index=False, max_colwidth=64))

    # ---------------------------------------------------- binary targets
    results = {}
    snapshot = {}
    for target in BINARY_TARGETS:
        if target not in features.columns:
            continue
        log.info("Training %s", target)
        result = train_binary_target(features, target)
        results[target] = result

        emit()
        emit("---")
        emit()
        emit("## `{}`".format(target))
        block("Split", result.split_description)
        for note in result.notes:
            emit()
            emit("> {}".format(note))

        if result.metrics.empty:
            continue
        block("Baseline vs improved", result.metrics.to_string(index=False))

        if result.calibration is not None:
            cal = result.calibration.summary()
            body = "\n".join("{:<22}: {}".format(k, v) for k, v in cal.items())
            block("Calibration", body)
            if result.reliability is not None:
                block("Reliability (equal-count bins)",
                      result.reliability.round(5).to_string(index=False))
            for column, table in (result.segment_calibration or {}).items():
                block("Calibration by {} — {}".format(
                          column.replace("_", " "), target),
                      table.to_string(index=False))

        # ---- confidence intervals and slice diagnostics -------------
        model, cols = result.models[result.champion]
        usable = features[features[target].notna()]
        usable = usable[mature_label_mask(usable, target)]
        split = time_aware_split(
            usable, purge_months=TARGET_HORIZON_MONTHS.get(target, 0),
            test_fraction=0.2,
        )
        if len(split.test):
            p_test = model.predict_proba(split.test[cols])[:, 1]
            if result.calibration is not None:
                p_test = result.calibration.apply(p_test)

            ci = bootstrap_metric_intervals(
                split.test[target], p_test, groups=split.test[LOAN_ID_COLUMN])
            if "roc_auc_point" in ci:
                body = chr(10).join([
                    "ROC-AUC  {roc_auc_point}  [{roc_auc_lo}, {roc_auc_hi}]",
                    "PR-AUC   {pr_auc_point}  [{pr_auc_lo}, {pr_auc_hi}]",
                    "",
                    "resampled over {n_clusters:,} loans, "
                    "{n_boot_usable} usable draws",
                ]).format(**ci)
                block("Confidence intervals — {}".format(target), body)
                snapshot.setdefault("intervals", {})[target] = ci

            threshold = float(np.quantile(p_test, 0.95))
            for segment in ("credit_score_band", "state"):
                if segment not in split.test.columns:
                    continue
                sl = slice_metrics(split.test, split.test[target], p_test,
                                   segment, threshold=threshold)
                if len(sl):
                    block("By {} — {}".format(segment, target),
                          sl.to_string(index=False))
                    snapshot.setdefault("slices", {}).setdefault(
                        target, {})[segment] = sl.to_dict(orient="records")

        joblib.dump(
            {"model": model, "columns": cols, "calibration": result.calibration,
             "target": target, "champion": result.champion},
            OUT_DIR / "{}.joblib".format(target),
        )
        snapshot[target] = {
            "champion": result.champion,
            "metrics": result.metrics.to_dict(orient="records"),
            "calibration": result.calibration.summary() if result.calibration else None,
            "prevalence": result.prevalence,
        }

    # ------------------------------------------------------- next_state
    log.info("Training next_state")
    ns = train_next_state(features)
    emit()
    emit("---")
    emit()
    emit("## `next_state` (hierarchical multiclass)")
    block("Split", ns.split_description)
    block("Model comparison", ns.metrics.to_string(index=False))
    for note in ns.notes:
        emit()
        emit("> {}".format(note))
    snapshot["next_state"] = {
        "champion": ns.champion,
        "metrics": ns.metrics.to_dict(orient="records"),
    }

    # ----------------------------------------- predictability ceiling
    log.info("Measuring predictability ceilings")
    ceilings = []
    for target in BINARY_TARGETS:
        if target not in features.columns:
            continue
        ceilings.append(predictability_ceiling(features, target))
    ceiling_df = pd.DataFrame(ceilings)
    if len(ceiling_df):
        show = [c for c in ("target", "temporal_roc_auc", "random_roc_auc",
                            "temporal_lift", "random_lift",
                            "share_lost_to_time")
                if c in ceiling_df.columns]
        block("Predictability ceiling: how much is lost to time",
              ceiling_df[show].to_string(index=False))
        emit()
        emit("A weak out-of-time score has two very different causes and "
             "opposite remedies. If the same model scores well under a "
             "random split, the features carry signal that does not "
             "survive the passage of time -- a drift problem. If it scores "
             "badly under both, the signal was never there and no feature "
             "work will help.")
        emit()
        emit("**The random column is a diagnostic ceiling, not a "
             "performance claim.** It lets the model see the future and "
             "must never be reported as deployment performance. Only the "
             "temporal column is a real estimate.")
        snapshot["predictability_ceiling"] = ceiling_df.to_dict(orient="records")

    # --------------------------------------------------------- summary
    rows = []
    for target, r in results.items():
        if r.metrics.empty:
            continue
        best = r.metrics[r.metrics.calibrated] if r.metrics.calibrated.any() else r.metrics
        best = best.sort_values("pr_auc", ascending=False).iloc[0]
        base = r.metrics[r.metrics.model.str.startswith("baseline")].iloc[0]
        rows.append({
            "target": target,
            "prevalence": best["prevalence"],
            "baseline_pr_auc": base["pr_auc"],
            "final_pr_auc": best["pr_auc"],
            "pr_auc_lift_over_base_rate": best["pr_auc_lift"],
            "roc_auc": best["roc_auc"],
            "recall_at_p50": best["recall_at_p50"],
            "brier": best["brier"],
            "ece": best["ece"],
        })
    summary = pd.DataFrame(rows)
    emit()
    emit("---")
    emit()
    block("Summary across targets", summary.to_string(index=False))

    (MODELS_DIR / "supervised_metrics.json").write_text(
        json.dumps(snapshot, indent=2, default=str), encoding="utf-8"
    )
    (DOCS_DIR / "model_performance_report.md").write_text(
        "\n".join(report) + "\n", encoding="utf-8"
    )
    print("\nWrote docs/model_performance_report.md")
    print("Wrote docs/feature_manifest.md")
    print("Wrote models/supervised_metrics.json")
    print("Wrote {} champion models to models/supervised/".format(len(results)))


if __name__ == "__main__":
    main()
